config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#index"
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :books, only: [:index, :show] do
    resources :words, only: [:new, :create, :show, :destroy]
  end
  post "/records/:id", to: "records#record", as: "record"
  get "/books/:id/learn", to: "records#learn", as: "learn"
  get "/books/:id/review", to: "records#review", as: "review"
  delete "/books/:id/giveup", to: "records#giveup", as: "giveup"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true
  has_many :words
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :word
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable
  validates_format_of :sid, with: /\A\d{10}\z/
  validates_presence_of :name
  validates_presence_of :major
  has_one :book
  has_many :records
end

app/models/word.rb
class Word < ApplicationRecord
  validates_presence_of :text
  belongs_to :book
  has_many :records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  # GET /books
  def index
    @books = [current_user.book]
    @books += Book.where user_id: nil
  end

  # GET /books/1
  def show
    @book = Book.find(params[:id])
    redirect_to books_path, alert: "没有权限查看该单词本！" unless @book.user.nil? || @book.user == current_user
    @words = @book.words.order(:id).page params[:page]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!

  # POST /records/1
  def record
    word = Word.find params[:id]
    if params[:remembered]
      record = word.records.find_by_user_id(current_user)
      if record
        record.time = Time.now
        record.save
      else
        word.records.create user: current_user, time: Time.now
      end
    end
    redirect_to learn_path(params[:book_id])
  end

  # GET /books/1/learn
  def learn
    book = Book.find params[:id]
    subquery = Record.where(user: current_user).to_sql
    unlearned = Word.joins("LEFT JOIN (#{subquery}) AS records ON records.word_id = words.id")
                    .where(book: book, records: { id: nil })
    word = unlearned.sample
    if word
      redirect_to [book, word]
    else
      redirect_to book, notice: "🎉 恭喜，所有单词都已经背完啦~"
    end
  end

  # GET /books/1/review
  def review
    @book = Book.find params[:id]
    @words = Word.includes(:records)
                 .where(book: @book, records: { user: current_user })
                 .order("records.id DESC")
    if @words.empty?
      redirect_to @book, notice: "👀 哎呀，目前还没背过任何单词~"
    else
      render
    end
  end

  # DELETE /books/1/giveup
  def giveup
    book = Book.find params[:id]
    current_user.records.each { |r| r.destroy if r.word.book == book }
    redirect_to book, notice: "1, 2... 空！已经把所有单词忘得干干净净了！"
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |user|
      next unless user.persisted?
      user.build_book(
        title: "我的词库",
        description: "定制自己的个性化词库",
        image_url: "shebang.png"
      )
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:sid, :name, :major])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:sid, :name, :major])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_book
  before_action :set_word, only: [:show, :destroy]
  before_action :authenticate_user!
  before_action :authenticate_book_ownership!, only: [:new, :create, :destroy]

  # GET /books/1/words/1
  def show
    redirect_to books_path, alert: "单词本中不存在该单词！" if @word.book != @book
    @custom_book = current_user.book
    @custom_word = @custom_book.words.build(@word.attributes)
    @exist = @custom_book.words.find_by_text(@word.text)
  end

  # GET /books/1/words/new
  def new
    @word = @book.words.build
  end

  # POST /books/1/words
  def create
    @word = @book.words.build(word_params)
    if @word.save
      respond_to do |format|
        format.html { redirect_to @book, notice: "单词添加成功！" }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js { render js: "alert('加入单词本失败！')" }
      end
    end
  end

  # DELETE /books/1/words/1
  def destroy
    @word.destroy
    redirect_to @book, notice: "单词删除成功！"
  end

  private
    def set_book
      @book = Book.find(params[:book_id])
    end

    def set_word
      @word = Word.find(params[:id])
    end

    def authenticate_book_ownership!
      redirect_to @book, alert: "没有权限编辑该单词本中的单词！" if @book.user != current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:text, :pronunciation, :translation, :book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? 'active' : ''
  end
end

app/views/books/index.html.slim
.container
  h1.page-title 单词本
  - @books.each do |book|
    .card.book-card
      = image_tag book.image_url, class: "card-img-top"
      .card-body
        h5.card-title = book.title
        p.card-text = book.description
        = link_to "进入", book, class: "btn btn-primary"

app/views/books/show.html.slim
.container
  nav.page-title
    ol.breadcrumb
      li.breadcrumb-item
        = link_to "首页", root_path
      li.breadcrumb-item
        = link_to "单词本", books_path
      li.breadcrumb-item.active
        = @book.title
  .row.justify-content-between
    .col-sm-3
      = image_tag @book.image_url, class: "rounded"
      p.book-description
        b = @book.description
        | （#{page_entries_info @words}）
      - unless @book.user
        = link_to "开始学习", learn_path(@book), class: "btn btn-block btn-dark"
        = link_to "快速复习", review_path(@book), class: "btn btn-block btn-secondary"
    .col-sm-8
      - if @book.user
        = link_to "添加单词", new_book_word_path(@book), class: "btn btn-primary btn-upper-right"
      table.table.table-hover
        thead
          tr
            th[scope="col"] = Word.human_attribute_name "text"
            th[scope="col"] = Word.human_attribute_name "pronunciation"
            th[scope="col"] = Word.human_attribute_name "translation"
            - if @book.user
              th[scope="col"]
        tbody
          - @words.each do |word|
            tr
              td = word.text
              td = word.pronunciation
              td = word.translation
              - if @book.user
                td = button_to "删除", [@book, word], method: "delete", class: "btn btn-danger", data: { confirm: "确认删除单词吗？" }
      = paginate @words

app/views/layouts/_navbar.slim
nav.navbar.navbar-expand-sm.navbar-light.bg-light
  = link_to "単語", root_path, class: "navbar-brand"
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbar-content"
    span.navbar-toggler-icon
  #navbar-content.collapse.navbar-collapse
    ul.navbar-nav.ml-auto
      - if user_signed_in?
        li.nav-item.dropdown
          a#navbar-dropdown.nav-link.dropdown-toggle href="#" role="button" data-toggle="dropdown"
            = current_user.email
          .dropdown-menu.dropdown-menu-right
            = link_to "我的单词本", books_path, class: "dropdown-item"
            = link_to "修改信息", edit_user_registration_path, class: "dropdown-item"
            = link_to "登出", destroy_user_session_path, method: "delete", class: "dropdown-item"
      - else
        li class="nav-item #{active_class new_user_registration_path}"
          = link_to "注册", new_user_registration_path, class: "nav-link"
        li class="nav-item #{active_class new_user_session_path}"
          = link_to "登录", new_user_session_path, class: "nav-link"
- if notice
  .alert.alert-primary role="alert"
    = notice
- if alert
  .alert.alert-danger role="alert"
    = alert

app/views/layouts/application.html.slim
doctype html
html
  head
    title 単語
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/navbar"
    = yield

app/views/pages/index.html.slim
.container
  .jumbotron
    h1.display-4 欢迎！
    p.lead 提供单词背诵计划、快速复习、个性词库等功能，助您轻松扩充词汇量
    = link_to "开始单词之旅", user_signed_in? ? books_path : new_user_session_path, class: "btn btn-primary"

app/views/records/review.html.slim
.container
  nav.page-title
    ol.breadcrumb
      li.breadcrumb-item
        = link_to "首页", root_path
      li.breadcrumb-item
        = link_to "单词本", books_path
      li.breadcrumb-item
        = link_to @book.title, @book
      li.breadcrumb-item.active
        | 复习
  .row.justify-content-between
    .col-sm-3.d-none.d-sm-block
      = image_tag @book.image_url
      p.book-description
        b = @book.description
        | （已学习 #{@words.count} 个单词）
      = link_to "返回", @book, class: "btn btn-block btn-secondary"
    .col-sm-8
      = button_to "放弃学习进度", giveup_path(@book), method: "delete", class: "btn btn-danger btn-upper-right", data: { confirm: "这会清空所有已背单词，确认要放弃学习进度吗？" }
      table.table.table-hover
        thead
          tr
            th[scope="col"] = Word.human_attribute_name "text"
            th[scope="col"] = Word.human_attribute_name "pronunciation"
            th[scope="col"] = Word.human_attribute_name "translation"
            th[scope="col"] 上次背诵时间
        tbody
          - @words.each do |word|
            tr
              td = word.text
              td = word.pronunciation
              td = word.translation
              td = time_ago_in_words(word.records.find_by_user_id(current_user).time) + "前"

app/views/words/new.html.slim
.container
  nav.page-title
    ol.breadcrumb
      li.breadcrumb-item
        = link_to "首页", root_path
      li.breadcrumb-item
        = link_to "单词本", books_path
      li.breadcrumb-item
        = link_to @book.title, @book
      li.breadcrumb-item.active
        | 添加单词
  .row
    .col-sm-3.d-none.d-sm-block
      = image_tag @book.image_url
      p.book-description
        b = @book.description
    .col-sm-5.offset-sm-2
      = form_for [@book, @word] do |f|
        - if @word.errors.any?
          .alert.alert-danger
            #error_explanation
              h2 = I18n.t "errors.messages.not_saved", count: @word.errors.count, resource: @word.class.model_name.human.downcase
              ul
                - @word.errors.full_messages.each do |message|
                  li = message
        .form-group
          = f.label :text
          = f.text_field :text, class: "form-control", required: true
        .form-group
          = f.label :pronunciation
          = f.text_field :pronunciation, class: "form-control"
        .form-group
          = f.label :translation
          = f.text_field :translation, class: "form-control"
        .actions
          = f.submit class: "btn btn-primary"

app/views/words/show.html.slim
.container
  nav.page-title
    ol.breadcrumb
      li.breadcrumb-item
        = link_to "首页", root_path
      li.breadcrumb-item
        = link_to "单词本", books_path
      li.breadcrumb-item
        = link_to @book.title, @book
      li.breadcrumb-item.active
        | 学习
  .row
    .col-sm-3.d-none.d-sm-block
      = image_tag @book.image_url
      p.book-description
        b = @book.description
      = link_to "返回", @book, class: "btn btn-block btn-secondary"
    .col-sm-5.offset-sm-2
      h1 = @word.text
      p.d-none.second-stage = @word.pronunciation
      p.d-none.second-stage = @word.translation
      button.btn.btn-secondary.first-stage[type="button" onclick="stage()"] 查看释义
      = link_to "记住了", record_path(@word, book_id: @book, remembered: true), method: "post", class: "btn btn-success d-none second-stage"
      = link_to "没记住", record_path(@word, book_id: @book), method: "post", class: "btn btn-danger d-none second-stage"
      = form_for @custom_word, url: book_words_path(@custom_book), remote: true, html: { class: "d-inline" } do |f|
        = f.hidden_field :text
        = f.hidden_field :pronunciation
        = f.hidden_field :translation
        = f.submit "加入我的词库", id: "add-to-custom-book", class: "btn btn-primary float-right d-none second-stage #{"disabled" if @exist}"